miss_ingredient = "Ingredient ids must be provided"
unauthorised = "You should be authorised"
duplicate_user = "User already exists"
required_fields = "Email, password and name are required fields"
incorrect_credentials = "email or password are incorrect"
